; generated by PrusaSlicer 2.1.1+win64 on 2020-02-29 at 17:36:37 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107 ; disable fan
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q3 S2
M73 P3 R2
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000 ; retract
G1 Z0.600 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.2
G1 X5.886 Y6.609 ; move to first skirt point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S1000 ; adjust acceleration
G1 F900
G1 X6.482 Y6.267 E0.02156 ; skirt
G1 X7.137 Y6.056 E0.02156 ; skirt
G1 X7.784 Y5.983 E0.02043 ; skirt
G1 X12.702 Y5.983 E0.15418 ; skirt
G1 X13.754 Y6.156 E0.03345 ; skirt
G1 X14.698 Y6.654 E0.03345 ; skirt
G1 X15.435 Y7.425 E0.03345 ; skirt
G1 X15.889 Y8.390 E0.03345 ; skirt
G1 X16.016 Y9.233 E0.02674 ; skirt
G1 X16.014 Y14.451 E0.16361 ; skirt
G1 X15.881 Y15.248 E0.02534 ; skirt
G1 X15.561 Y15.986 E0.02520 ; skirt
G1 X15.105 Y16.593 E0.02380 ; skirt
G1 X14.527 Y17.077 E0.02366 ; skirt
G1 X13.850 Y17.421 E0.02380 ; skirt
G1 X13.112 Y17.601 E0.02380 ; skirt
G1 X7.620 Y17.621 E0.17221 ; skirt
G1 X6.855 Y17.482 E0.02436 ; skirt
G1 X6.148 Y17.171 E0.02422 ; skirt
G1 X5.541 Y16.715 E0.02380 ; skirt
G1 X5.054 Y16.133 E0.02380 ; skirt
G1 X4.712 Y15.456 E0.02380 ; skirt
G1 X4.532 Y14.718 E0.02380 ; skirt
G1 X4.513 Y9.100 E0.17613 ; skirt
G1 X4.651 Y8.336 E0.02436 ; skirt
G1 X4.963 Y7.624 E0.02436 ; skirt
G1 X5.373 Y7.067 E0.02170 ; skirt
G1 X5.841 Y6.649 E0.01967 ; skirt
G1 F8640
G1 X6.482 Y6.267 E-0.17232 ; wipe and retract
G1 X7.137 Y6.056 E-0.15874 ; wipe and retract
G1 X7.784 Y5.983 E-0.15047 ; wipe and retract
G1 X8.990 Y5.983 E-0.27847 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
G1 X7.276 Y6.412 ; move to first skirt point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X12.701 Y6.360 E0.17011 ; skirt
G1 X13.650 Y6.519 E0.03016 ; skirt
G1 X14.494 Y6.972 E0.03003 ; skirt
G1 X15.149 Y7.676 E0.03016 ; skirt
G1 X15.543 Y8.554 E0.03016 ; skirt
G1 X15.640 Y9.258 E0.02227 ; skirt
G1 X15.637 Y14.443 E0.16258 ; skirt
G1 X15.510 Y15.172 E0.02319 ; skirt
G1 X15.206 Y15.846 E0.02319 ; skirt
G1 X14.794 Y16.372 E0.02095 ; skirt
G1 X14.271 Y16.794 E0.02108 ; skirt
G1 X13.669 Y17.085 E0.02095 ; skirt
G1 X13.017 Y17.233 E0.02095 ; skirt
G1 X7.645 Y17.244 E0.16846 ; skirt
G1 X6.942 Y17.114 E0.02240 ; skirt
G1 X6.288 Y16.816 E0.02253 ; skirt
G1 X5.762 Y16.404 E0.02095 ; skirt
G1 X5.340 Y15.881 E0.02108 ; skirt
G1 X5.048 Y15.275 E0.02108 ; skirt
G1 X4.901 Y14.619 E0.02108 ; skirt
G1 X4.889 Y9.125 E0.17226 ; skirt
G1 X5.020 Y8.418 E0.02253 ; skirt
G1 X5.318 Y7.764 E0.02253 ; skirt
G1 X5.692 Y7.278 E0.01923 ; skirt
G1 X6.154 Y6.882 E0.01910 ; skirt
G1 X6.689 Y6.589 E0.01910 ; skirt
G1 X7.219 Y6.429 E0.01735 ; skirt
G1 X7.320 Y6.796 F10800.000 ; move to first skirt point
G1 F900
G1 X7.404 Y6.772 E0.00272 ; skirt
G1 X12.701 Y6.737 E0.16610 ; skirt
G1 X13.540 Y6.880 E0.02668 ; skirt
G1 X14.286 Y7.288 E0.02668 ; skirt
G1 X14.857 Y7.919 E0.02668 ; skirt
G1 X15.191 Y8.701 E0.02668 ; skirt
G1 X15.263 Y9.274 E0.01808 ; skirt
G1 X15.260 Y14.430 E0.16168 ; skirt
G1 X15.140 Y15.090 E0.02103 ; skirt
G1 X14.854 Y15.697 E0.02103 ; skirt
G1 X14.487 Y16.146 E0.01820 ; skirt
G1 X14.027 Y16.501 E0.01820 ; skirt
G1 X13.500 Y16.744 E0.01820 ; skirt
G1 X12.932 Y16.862 E0.01820 ; skirt
G1 X7.669 Y16.868 E0.16503 ; skirt
G1 X7.025 Y16.744 E0.02054 ; skirt
G1 X6.437 Y16.464 E0.02042 ; skirt
G1 X5.988 Y16.097 E0.01820 ; skirt
G1 X5.633 Y15.638 E0.01820 ; skirt
G1 X5.389 Y15.107 E0.01832 ; skirt
G1 X5.272 Y14.538 E0.01820 ; skirt
G1 X5.266 Y9.149 E0.16898 ; skirt
G1 X5.388 Y8.505 E0.02054 ; skirt
G1 X5.670 Y7.914 E0.02054 ; skirt
G1 X6.004 Y7.498 E0.01672 ; skirt
G1 X6.416 Y7.160 E0.01672 ; skirt
G1 X6.890 Y6.915 E0.01672 ; skirt
G1 X7.262 Y6.812 E0.01212 ; skirt
G1 X6.667 Y7.447 F10800.000 ; move to first skirt point
G1 F900
G1 X7.515 Y7.137 E0.02833 ; skirt
G1 X12.701 Y7.114 E0.16260 ; skirt
G1 X13.428 Y7.240 E0.02315 ; skirt
G1 X14.076 Y7.603 E0.02326 ; skirt
G1 X14.562 Y8.158 E0.02315 ; skirt
G1 X14.837 Y8.844 E0.02315 ; skirt
G1 X14.883 Y14.413 E0.17464 ; skirt
G1 X14.773 Y15.001 E0.01873 ; skirt
G1 X14.508 Y15.536 E0.01873 ; skirt
G1 X14.188 Y15.910 E0.01544 ; skirt
G1 X13.792 Y16.202 E0.01544 ; skirt
G1 X13.340 Y16.399 E0.01544 ; skirt
G1 X12.856 Y16.490 E0.01544 ; skirt
G1 X7.695 Y16.492 E0.16182 ; skirt
G1 X7.123 Y16.380 E0.01828 ; skirt
G1 X6.598 Y16.118 E0.01839 ; skirt
G1 X6.224 Y15.798 E0.01544 ; skirt
G1 X5.932 Y15.402 E0.01544 ; skirt
G1 X5.735 Y14.950 E0.01544 ; skirt
G1 X5.644 Y14.467 E0.01544 ; skirt
G1 X5.642 Y9.175 E0.16591 ; skirt
G1 X5.754 Y8.599 E0.01839 ; skirt
G1 X6.016 Y8.074 E0.01839 ; skirt
G1 X6.623 Y7.489 E0.02645 ; skirt
; printing object cube.stl id:0 copy 0
G1 F8640
G1 X7.515 Y7.137 E-0.22137 ; wipe and retract
G1 X9.848 Y7.127 E-0.53863 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
G1 X8.414 Y9.890 ; move to first perimeter point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X12.110 Y9.890 E0.11589 ; perimeter
G1 X12.110 Y13.720 E0.12010 ; perimeter
G1 X8.414 Y13.720 E0.11589 ; perimeter
G1 X8.414 Y9.950 E0.11821 ; perimeter
G1 X8.037 Y9.513 F10800.000 ; move to first perimeter point
G1 F900
G1 X12.487 Y9.513 E0.13954 ; perimeter
G1 X12.487 Y14.097 E0.14374 ; perimeter
G1 X8.037 Y14.097 E0.13954 ; perimeter
G1 X8.037 Y9.573 E0.14186 ; perimeter
G1 X8.423 Y9.618 F10800.000 ; move inwards before travel
G1 F8640
G1 X11.328 Y9.528 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
G1 X8.527 Y12.820 ; move to first infill point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X9.144 Y13.437 E0.02824 ; infill
G1 X9.694 Y13.437 E0.01778 ; infill
G1 X8.697 Y12.440 E0.04563 ; infill
G1 X8.697 Y11.890 E0.01778 ; infill
G1 X10.244 Y13.437 E0.07078 ; infill
G1 X10.794 Y13.437 E0.01778 ; infill
G1 X8.697 Y11.340 E0.09593 ; infill
G1 X8.697 Y10.790 E0.01778 ; infill
G1 X11.344 Y13.437 E0.12107 ; infill
G1 X11.827 Y13.437 E0.01562 ; infill
G1 X11.827 Y13.370 E0.00216 ; infill
G1 X8.697 Y10.240 E0.14316 ; infill
G1 X8.697 Y10.173 E0.00217 ; infill
G1 X9.180 Y10.173 E0.01561 ; infill
G1 X11.827 Y12.821 E0.12108 ; infill
G1 X11.827 Y12.271 E0.01778 ; infill
G1 X9.729 Y10.173 E0.09593 ; infill
G1 X10.279 Y10.173 E0.01778 ; infill
G1 X11.827 Y11.721 E0.07078 ; infill
G1 X11.827 Y11.171 E0.01778 ; infill
G1 X10.829 Y10.173 E0.04563 ; infill
G1 X11.379 Y10.173 E0.01778 ; infill
G1 X11.997 Y10.790 E0.02824 ; infill
; stop printing object cube.stl id:0 copy 0
M106 S255 ; enable fan
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.35


G1 F8640
G1 X11.379 Y10.173 E-0.20168 ; wipe and retract
G1 X10.829 Y10.173 E-0.12699 ; wipe and retract
G1 X11.827 Y11.171 E-0.32586 ; wipe and retract
G1 X11.827 Y11.627 E-0.10548 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.35
M104 S210 ; set temperature
G1 X15.435 Y7.425 ; move to first skirt point
G1 Z0.350 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X15.889 Y8.390 E0.02580 ; skirt
G1 X16.016 Y9.233 E0.02063 ; skirt
G1 X16.014 Y14.451 E0.12620 ; skirt
G1 X15.881 Y15.248 E0.01955 ; skirt
G1 X15.561 Y15.986 E0.01944 ; skirt
G1 X15.105 Y16.593 E0.01836 ; skirt
G1 X14.527 Y17.077 E0.01825 ; skirt
G1 X13.850 Y17.421 E0.01836 ; skirt
G1 X13.112 Y17.601 E0.01836 ; skirt
G1 X7.620 Y17.621 E0.13284 ; skirt
G1 X6.855 Y17.482 E0.01879 ; skirt
G1 X6.148 Y17.171 E0.01868 ; skirt
G1 X5.541 Y16.715 E0.01836 ; skirt
G1 X5.054 Y16.133 E0.01836 ; skirt
G1 X4.712 Y15.456 E0.01836 ; skirt
G1 X4.532 Y14.718 E0.01836 ; skirt
G1 X4.513 Y9.100 E0.13586 ; skirt
G1 X4.651 Y8.336 E0.01879 ; skirt
G1 X4.963 Y7.624 E0.01879 ; skirt
G1 X5.373 Y7.067 E0.01673 ; skirt
G1 X5.886 Y6.609 E0.01663 ; skirt
G1 X6.482 Y6.267 E0.01663 ; skirt
G1 X7.137 Y6.056 E0.01663 ; skirt
G1 X7.784 Y5.983 E0.01576 ; skirt
G1 X12.702 Y5.983 E0.11893 ; skirt
G1 X13.754 Y6.156 E0.02580 ; skirt
G1 X14.698 Y6.654 E0.02580 ; skirt
G1 X15.393 Y7.381 E0.02435 ; skirt
; printing object cube.stl id:0 copy 0
G1 F8640
G1 X15.889 Y8.390 E-0.25948 ; wipe and retract
G1 X16.016 Y9.233 E-0.19694 ; wipe and retract
G1 X16.016 Y10.548 E-0.30359 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.950 F10800.000 ; lift Z
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z0.350 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.950 F10800.000 ; lift Z
G1 X9.492 Y10.071 ; move to first infill point
G1 Z0.350 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X8.783 Y10.780 E0.02768 ; infill
G1 X8.783 Y11.406 E0.01728 ; infill
G1 X9.930 Y10.259 E0.04478 ; infill
G1 X10.556 Y10.259 E0.01728 ; infill
G1 X8.783 Y12.032 E0.06922 ; infill
G1 X8.783 Y12.658 E0.01728 ; infill
G1 X11.182 Y10.259 E0.09365 ; infill
G1 X11.741 Y10.259 E0.01543 ; infill
G1 X11.741 Y10.326 E0.00185 ; infill
G1 X8.783 Y13.284 E0.11548 ; infill
G1 X8.783 Y13.351 E0.00185 ; infill
G1 X9.342 Y13.351 E0.01543 ; infill
G1 X11.741 Y10.952 E0.09366 ; infill
G1 X11.741 Y11.578 E0.01728 ; infill
G1 X9.968 Y13.351 E0.06922 ; infill
G1 X10.594 Y13.351 E0.01728 ; infill
G1 X11.741 Y12.204 E0.04478 ; infill
G1 X11.741 Y12.830 E0.01728 ; infill
G1 X11.032 Y13.539 E0.02769 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.5


G1 F8640
G1 X11.741 Y12.830 E-0.23160 ; wipe and retract
G1 X11.741 Y12.204 E-0.14454 ; wipe and retract
G1 X10.594 Y13.351 E-0.37462 ; wipe and retract
G1 X10.554 Y13.351 E-0.00924 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.950 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.5
G1 X14.698 Y6.654 ; move to first skirt point
G1 Z0.500 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X15.435 Y7.425 E0.02580 ; skirt
G1 X15.889 Y8.390 E0.02580 ; skirt
G1 X16.016 Y9.233 E0.02063 ; skirt
G1 X16.014 Y14.451 E0.12620 ; skirt
G1 X15.881 Y15.248 E0.01955 ; skirt
G1 X15.561 Y15.986 E0.01944 ; skirt
G1 X15.105 Y16.593 E0.01836 ; skirt
G1 X14.527 Y17.077 E0.01825 ; skirt
G1 X13.850 Y17.421 E0.01836 ; skirt
G1 X13.112 Y17.601 E0.01836 ; skirt
G1 X7.620 Y17.621 E0.13284 ; skirt
G1 X6.855 Y17.482 E0.01879 ; skirt
G1 X6.148 Y17.171 E0.01868 ; skirt
G1 X5.541 Y16.715 E0.01836 ; skirt
G1 X5.054 Y16.133 E0.01836 ; skirt
G1 X4.712 Y15.456 E0.01836 ; skirt
G1 X4.532 Y14.718 E0.01836 ; skirt
G1 X4.513 Y9.100 E0.13586 ; skirt
G1 X4.651 Y8.336 E0.01879 ; skirt
G1 X4.963 Y7.624 E0.01879 ; skirt
G1 X5.373 Y7.067 E0.01673 ; skirt
G1 X5.886 Y6.609 E0.01663 ; skirt
G1 X6.482 Y6.267 E0.01663 ; skirt
G1 X7.137 Y6.056 E0.01663 ; skirt
G1 X7.784 Y5.983 E0.01576 ; skirt
G1 X12.702 Y5.983 E0.11893 ; skirt
G1 X13.754 Y6.156 E0.02580 ; skirt
G1 X14.645 Y6.626 E0.02435 ; skirt
; printing object cube.stl id:0 copy 0
G1 F8640
G1 X15.435 Y7.425 E-0.25948 ; wipe and retract
G1 X15.889 Y8.390 E-0.24630 ; wipe and retract
G1 X16.016 Y9.233 E-0.19694 ; wipe and retract
G1 X16.016 Y9.481 E-0.05729 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.100 F10800.000 ; lift Z
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z0.500 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.100 F10800.000 ; lift Z
G1 X11.929 Y10.968 ; move to first infill point
G1 Z0.500 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X11.220 Y10.259 E0.02769 ; infill
G1 X10.594 Y10.259 E0.01728 ; infill
G1 X11.741 Y11.406 E0.04478 ; infill
G1 X11.741 Y12.032 E0.01728 ; infill
G1 X9.968 Y10.259 E0.06922 ; infill
G1 X9.342 Y10.259 E0.01728 ; infill
G1 X11.741 Y12.658 E0.09366 ; infill
G1 X11.741 Y13.284 E0.01728 ; infill
G1 X8.783 Y10.326 E0.11548 ; infill
G1 X8.783 Y10.952 E0.01728 ; infill
G1 X11.182 Y13.351 E0.09365 ; infill
G1 X10.556 Y13.351 E0.01728 ; infill
G1 X8.783 Y11.578 E0.06922 ; infill
G1 X8.783 Y12.204 E0.01728 ; infill
G1 X9.930 Y13.351 E0.04478 ; infill
G1 X9.304 Y13.351 E0.01728 ; infill
G1 X8.595 Y12.642 E0.02768 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.65


G1 F8640
G1 X9.304 Y13.351 E-0.23156 ; wipe and retract
G1 X9.930 Y13.351 E-0.14454 ; wipe and retract
G1 X8.783 Y12.204 E-0.37458 ; wipe and retract
G1 X8.783 Y12.164 E-0.00932 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.100 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.65
; printing object cube.stl id:0 copy 0
G1 X8.470 Y13.664 ; move to first perimeter point
G1 Z0.650 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.530 Y13.664 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.052 Y14.082 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.112 Y14.082 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.153 Y13.695 F10800.000 ; move inwards before travel
G1 F8640
G1 X8.068 Y10.791 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.250 F10800.000 ; lift Z
G1 X11.032 Y13.539 ; move to first infill point
G1 Z0.650 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X11.741 Y12.830 E0.02769 ; infill
G1 X11.741 Y12.204 E0.01728 ; infill
G1 X10.594 Y13.351 E0.04478 ; infill
G1 X9.968 Y13.351 E0.01728 ; infill
G1 X11.741 Y11.578 E0.06922 ; infill
G1 X11.741 Y10.952 E0.01728 ; infill
G1 X9.342 Y13.351 E0.09366 ; infill
G1 X8.783 Y13.351 E0.01543 ; infill
G1 X8.783 Y13.284 E0.00185 ; infill
G1 X11.741 Y10.326 E0.11548 ; infill
G1 X11.741 Y10.259 E0.00185 ; infill
G1 X11.182 Y10.259 E0.01543 ; infill
G1 X8.783 Y12.658 E0.09365 ; infill
G1 X8.783 Y12.032 E0.01728 ; infill
G1 X10.556 Y10.259 E0.06922 ; infill
G1 X9.930 Y10.259 E0.01728 ; infill
G1 X8.783 Y11.406 E0.04478 ; infill
G1 X8.783 Y10.780 E0.01728 ; infill
G1 X9.492 Y10.071 E0.02768 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


G1 F8640
G1 X8.783 Y10.780 E-0.23156 ; wipe and retract
G1 X8.783 Y11.406 E-0.14454 ; wipe and retract
G1 X9.930 Y10.259 E-0.37458 ; wipe and retract
G1 X9.970 Y10.259 E-0.00932 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.250 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.8
; printing object cube.stl id:0 copy 0
G1 X8.470 Y9.946 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y10.006 E0.09533 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.052 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.588 E0.11711 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.438 Y9.633 F10800.000 ; move inwards before travel
G1 F8640
G1 X11.343 Y9.543 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.400 F10800.000 ; lift Z
G1 X8.595 Y12.642 ; move to first infill point
G1 Z0.800 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X9.304 Y13.351 E0.02768 ; infill
G1 X9.930 Y13.351 E0.01728 ; infill
G1 X8.783 Y12.204 E0.04478 ; infill
G1 X8.783 Y11.578 E0.01728 ; infill
G1 X10.556 Y13.351 E0.06922 ; infill
G1 X11.182 Y13.351 E0.01728 ; infill
G1 X8.783 Y10.952 E0.09365 ; infill
G1 X8.783 Y10.326 E0.01728 ; infill
G1 X11.741 Y13.284 E0.11548 ; infill
G1 X11.741 Y12.658 E0.01728 ; infill
G1 X9.342 Y10.259 E0.09366 ; infill
G1 X9.968 Y10.259 E0.01728 ; infill
G1 X11.741 Y12.032 E0.06922 ; infill
G1 X11.741 Y11.406 E0.01728 ; infill
G1 X10.594 Y10.259 E0.04478 ; infill
G1 X11.220 Y10.259 E0.01728 ; infill
G1 X11.929 Y10.968 E0.02769 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.95


G1 F8640
G1 X11.220 Y10.259 E-0.23160 ; wipe and retract
G1 X10.594 Y10.259 E-0.14454 ; wipe and retract
G1 X11.741 Y11.406 E-0.37462 ; wipe and retract
G1 X11.741 Y11.446 E-0.00924 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.400 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.95
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z0.950 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.550 F10800.000 ; lift Z
G1 X8.783 Y12.534 ; move to first infill point
G1 Z0.950 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X8.947 Y12.574 E0.00441 ; infill
G1 X9.284 Y12.603 E0.00879 ; infill
G1 X9.396 Y12.580 E0.00298 ; infill
G1 X9.564 Y12.470 E0.00524 ; infill
G1 X9.620 Y12.403 E0.00228 ; infill
G1 X9.844 Y11.991 E0.01221 ; infill
G1 X10.068 Y11.514 E0.01374 ; infill
G1 X10.404 Y10.930 E0.01756 ; infill
G1 X10.741 Y10.524 E0.01373 ; infill
G1 X11.055 Y10.259 E0.01071 ; infill
G1 X10.792 Y13.351 E0.08086 ; infill
G1 X10.517 Y13.259 E0.00757 ; infill
G1 X10.068 Y13.174 E0.01189 ; infill
G1 X9.844 Y13.198 E0.00587 ; infill
G1 X9.732 Y13.258 E0.00331 ; infill
G1 X9.643 Y13.351 E0.00335 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.1


G1 F8640
G1 X9.732 Y13.258 E-0.02967 ; wipe and retract
G1 X9.844 Y13.198 E-0.02934 ; wipe and retract
G1 X10.068 Y13.174 E-0.05206 ; wipe and retract
G1 X10.517 Y13.259 E-0.10534 ; wipe and retract
G1 X10.792 Y13.351 E-0.06708 ; wipe and retract
G1 X10.967 Y11.295 E-0.47651 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.550 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.1
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z1.100 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.700 F10800.000 ; lift Z
G1 X11.089 Y10.259 ; move to first infill point
G1 Z1.100 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X10.741 Y10.506 E0.01113 ; infill
G1 X10.517 Y10.720 E0.00808 ; infill
G1 X10.292 Y10.987 E0.00907 ; infill
G1 X9.844 Y11.657 E0.02102 ; infill
G1 X9.620 Y11.973 E0.01009 ; infill
G1 X9.508 Y12.095 E0.00433 ; infill
G1 X9.396 Y12.190 E0.00381 ; infill
G1 X9.172 Y12.303 E0.00654 ; infill
G1 X8.947 Y12.345 E0.00594 ; infill
G1 X8.783 Y12.343 E0.00429 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.25


G1 F8640
G1 X8.947 Y12.345 E-0.03800 ; wipe and retract
G1 X9.172 Y12.303 E-0.05265 ; wipe and retract
G1 X9.396 Y12.190 E-0.05796 ; wipe and retract
G1 X9.508 Y12.095 E-0.03380 ; wipe and retract
G1 X9.620 Y11.973 E-0.03836 ; wipe and retract
G1 X9.844 Y11.657 E-0.08940 ; wipe and retract
G1 X10.292 Y10.987 E-0.18625 ; wipe and retract
G1 X10.517 Y10.720 E-0.08042 ; wipe and retract
G1 X10.741 Y10.506 E-0.07157 ; wipe and retract
G1 X11.089 Y10.259 E-0.09864 ; wipe and retract
G1 E-0.05295 F2100.00000 ; retract
G1 Z1.700 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.25
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z1.250 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z1.850 F10800.000 ; lift Z
G1 X11.113 Y10.259 ; move to first infill point
G1 Z1.250 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X10.965 Y10.334 E0.00433 ; infill
G1 X10.517 Y10.659 E0.01443 ; infill
G1 X10.292 Y10.883 E0.00825 ; infill
G1 X9.620 Y11.714 E0.02786 ; infill
G1 X9.396 Y11.932 E0.00815 ; infill
G1 X9.172 Y12.077 E0.00695 ; infill
G1 X9.060 Y12.124 E0.00317 ; infill
G1 X8.783 Y12.184 E0.00737 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4


G1 F8640
G1 X9.060 Y12.124 E-0.06534 ; wipe and retract
G1 X9.172 Y12.077 E-0.02811 ; wipe and retract
G1 X9.396 Y11.932 E-0.06160 ; wipe and retract
G1 X9.620 Y11.714 E-0.07220 ; wipe and retract
G1 X10.292 Y10.883 E-0.24686 ; wipe and retract
G1 X10.517 Y10.659 E-0.07314 ; wipe and retract
G1 X10.965 Y10.334 E-0.12785 ; wipe and retract
G1 X11.113 Y10.259 E-0.03833 ; wipe and retract
G1 E-0.08656 F2100.00000 ; retract
G1 Z1.850 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.4
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z1.400 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.000 F10800.000 ; lift Z
G1 X11.121 Y10.259 ; move to first infill point
G1 Z1.400 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X10.741 Y10.441 E0.01098 ; infill
G1 X10.517 Y10.594 E0.00706 ; infill
G1 X10.292 Y10.784 E0.00766 ; infill
G1 X9.620 Y11.515 E0.02588 ; infill
G1 X9.396 Y11.731 E0.00811 ; infill
G1 X9.060 Y11.953 E0.01051 ; infill
G1 X8.783 Y12.048 E0.00762 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.55


G1 F8640
G1 X9.060 Y11.953 E-0.06749 ; wipe and retract
G1 X9.396 Y11.731 E-0.09311 ; wipe and retract
G1 X9.620 Y11.515 E-0.07187 ; wipe and retract
G1 X10.292 Y10.784 E-0.22934 ; wipe and retract
G1 X10.517 Y10.594 E-0.06788 ; wipe and retract
G1 X10.741 Y10.441 E-0.06259 ; wipe and retract
G1 X11.121 Y10.259 E-0.09728 ; wipe and retract
G1 E-0.11044 F2100.00000 ; retract
G1 Z2.000 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.55
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z1.550 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
M73 Q59 S1
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
M73 P59 R1
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.150 F10800.000 ; lift Z
G1 X11.099 Y10.259 ; move to first infill point
G1 Z1.550 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X10.741 Y10.396 E0.01000 ; infill
G1 X10.517 Y10.523 E0.00671 ; infill
G1 X10.292 Y10.685 E0.00721 ; infill
G1 X10.068 Y10.884 E0.00780 ; infill
G1 X9.396 Y11.560 E0.02485 ; infill
G1 X9.060 Y11.806 E0.01085 ; infill
G1 X8.783 Y11.930 E0.00789 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.7


G1 F8640
G1 X9.060 Y11.806 E-0.06994 ; wipe and retract
G1 X9.396 Y11.560 E-0.09619 ; wipe and retract
G1 X10.068 Y10.884 E-0.22024 ; wipe and retract
G1 X10.292 Y10.685 E-0.06913 ; wipe and retract
G1 X10.517 Y10.523 E-0.06390 ; wipe and retract
G1 X10.741 Y10.396 E-0.05948 ; wipe and retract
G1 X11.099 Y10.259 E-0.08862 ; wipe and retract
G1 E-0.13250 F2100.00000 ; retract
G1 Z2.150 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.7
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z1.700 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.300 F10800.000 ; lift Z
G1 X11.012 Y10.259 ; move to first infill point
G1 Z1.700 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X10.741 Y10.342 E0.00738 ; infill
G1 X10.517 Y10.445 E0.00643 ; infill
G1 X10.292 Y10.583 E0.00686 ; infill
G1 X10.068 Y10.758 E0.00741 ; infill
G1 X9.172 Y11.595 E0.03196 ; infill
G1 X8.947 Y11.744 E0.00702 ; infill
G1 X8.783 Y11.825 E0.00478 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.85


G1 F8640
G1 X8.947 Y11.744 E-0.04232 ; wipe and retract
G1 X9.172 Y11.595 E-0.06218 ; wipe and retract
G1 X10.068 Y10.758 E-0.28321 ; wipe and retract
G1 X10.292 Y10.583 E-0.06563 ; wipe and retract
G1 X10.517 Y10.445 E-0.06076 ; wipe and retract
G1 X10.741 Y10.342 E-0.05699 ; wipe and retract
G1 X11.012 Y10.259 E-0.06544 ; wipe and retract
G1 E-0.16347 F2100.00000 ; retract
G1 Z2.300 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.85
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z1.850 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.450 F10800.000 ; lift Z
G1 X9.493 Y10.071 ; move to first infill (bridge) point
G1 Z1.850 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F1800
G1 X8.778 Y10.785 E0.05088 ; infill (bridge)
G1 X8.778 Y11.411 E0.03151 ; infill (bridge)
G1 X9.935 Y10.254 E0.08238 ; infill (bridge)
G1 X10.561 Y10.254 E0.03151 ; infill (bridge)
G1 X8.778 Y12.037 E0.12694 ; infill (bridge)
G1 X8.778 Y12.663 E0.03151 ; infill (bridge)
G1 X11.187 Y10.254 E0.17150 ; infill (bridge)
G1 X11.746 Y10.254 E0.02814 ; infill (bridge)
G1 X11.746 Y10.321 E0.00337 ; infill (bridge)
G1 X8.778 Y13.289 E0.21130 ; infill (bridge)
G1 X8.778 Y13.356 E0.00338 ; infill (bridge)
G1 X9.337 Y13.356 E0.02813 ; infill (bridge)
G1 X11.746 Y10.947 E0.17151 ; infill (bridge)
G1 X11.746 Y11.573 E0.03151 ; infill (bridge)
G1 X9.963 Y13.356 E0.12695 ; infill (bridge)
G1 X10.589 Y13.356 E0.03151 ; infill (bridge)
G1 X11.746 Y12.199 E0.08238 ; infill (bridge)
G1 X11.746 Y12.825 E0.03151 ; infill (bridge)
G1 X11.031 Y13.540 E0.05088 ; infill (bridge)
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2


G1 F8640
G1 X11.746 Y12.825 E-0.23340 ; wipe and retract
G1 X11.746 Y12.199 E-0.14454 ; wipe and retract
G1 X10.589 Y13.356 E-0.37790 ; wipe and retract
G1 X10.571 Y13.356 E-0.00416 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.450 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;2
; printing object cube.stl id:0 copy 0
G1 X12.054 Y13.664 ; move to first perimeter point
G1 Z2.000 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.604 E0.09533 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y14.082 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.022 E0.11711 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.086 Y13.977 F10800.000 ; move inwards before travel
G1 F8640
G1 X9.181 Y14.067 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.600 F10800.000 ; lift Z
G1 X11.929 Y10.968 ; move to first infill point
G1 Z2.000 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X11.220 Y10.259 E0.02769 ; infill
G1 X10.594 Y10.259 E0.01728 ; infill
G1 X11.741 Y11.406 E0.04478 ; infill
G1 X11.741 Y12.032 E0.01728 ; infill
G1 X9.968 Y10.259 E0.06922 ; infill
G1 X9.342 Y10.259 E0.01728 ; infill
G1 X11.741 Y12.658 E0.09366 ; infill
G1 X11.741 Y13.284 E0.01728 ; infill
G1 X8.783 Y10.326 E0.11548 ; infill
G1 X8.783 Y10.952 E0.01728 ; infill
G1 X11.182 Y13.351 E0.09365 ; infill
G1 X10.556 Y13.351 E0.01728 ; infill
G1 X8.783 Y11.578 E0.06922 ; infill
G1 X8.783 Y12.204 E0.01728 ; infill
G1 X9.930 Y13.351 E0.04478 ; infill
G1 X9.304 Y13.351 E0.01728 ; infill
G1 X8.595 Y12.642 E0.02768 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.15


G1 F8640
G1 X9.304 Y13.351 E-0.23156 ; wipe and retract
G1 X9.930 Y13.351 E-0.14454 ; wipe and retract
G1 X8.783 Y12.204 E-0.37458 ; wipe and retract
G1 X8.783 Y12.164 E-0.00932 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.600 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.15
; printing object cube.stl id:0 copy 0
G1 X8.470 Y13.664 ; move to first perimeter point
G1 Z2.150 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.530 Y13.664 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.052 Y14.082 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.112 Y14.082 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.153 Y13.695 F10800.000 ; move inwards before travel
G1 F8640
G1 X8.068 Y10.791 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.750 F10800.000 ; lift Z
G1 X11.032 Y13.539 ; move to first infill point
G1 Z2.150 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X11.741 Y12.830 E0.02769 ; infill
G1 X11.741 Y12.204 E0.01728 ; infill
G1 X10.594 Y13.351 E0.04478 ; infill
G1 X9.968 Y13.351 E0.01728 ; infill
G1 X11.741 Y11.578 E0.06922 ; infill
G1 X11.741 Y10.952 E0.01728 ; infill
G1 X9.342 Y13.351 E0.09366 ; infill
G1 X8.783 Y13.351 E0.01543 ; infill
G1 X8.783 Y13.284 E0.00185 ; infill
G1 X11.741 Y10.326 E0.11548 ; infill
G1 X11.741 Y10.259 E0.00185 ; infill
G1 X11.182 Y10.259 E0.01543 ; infill
G1 X8.783 Y12.658 E0.09365 ; infill
G1 X8.783 Y12.032 E0.01728 ; infill
G1 X10.556 Y10.259 E0.06922 ; infill
G1 X9.930 Y10.259 E0.01728 ; infill
G1 X8.783 Y11.406 E0.04478 ; infill
G1 X8.783 Y10.780 E0.01728 ; infill
G1 X9.492 Y10.071 E0.02768 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.3


G1 F8640
G1 X8.783 Y10.780 E-0.23156 ; wipe and retract
G1 X8.783 Y11.406 E-0.14454 ; wipe and retract
G1 X9.930 Y10.259 E-0.37458 ; wipe and retract
G1 X9.970 Y10.259 E-0.00932 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.750 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.3
; printing object cube.stl id:0 copy 0
G1 X8.470 Y9.946 ; move to first perimeter point
G1 Z2.300 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y10.006 E0.09533 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.052 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.588 E0.11711 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.438 Y9.633 F10800.000 ; move inwards before travel
G1 F8640
G1 X11.343 Y9.543 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.900 F10800.000 ; lift Z
G1 X8.595 Y12.642 ; move to first infill point
G1 Z2.300 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X9.304 Y13.351 E0.02768 ; infill
G1 X9.930 Y13.351 E0.01728 ; infill
G1 X8.783 Y12.204 E0.04478 ; infill
G1 X8.783 Y11.578 E0.01728 ; infill
G1 X10.556 Y13.351 E0.06922 ; infill
G1 X11.182 Y13.351 E0.01728 ; infill
G1 X8.783 Y10.952 E0.09365 ; infill
G1 X8.783 Y10.326 E0.01728 ; infill
G1 X11.741 Y13.284 E0.11548 ; infill
G1 X11.741 Y12.658 E0.01728 ; infill
G1 X9.342 Y10.259 E0.09366 ; infill
G1 X9.968 Y10.259 E0.01728 ; infill
G1 X11.741 Y12.032 E0.06922 ; infill
G1 X11.741 Y11.406 E0.01728 ; infill
G1 X10.594 Y10.259 E0.04478 ; infill
G1 X11.220 Y10.259 E0.01728 ; infill
G1 X11.929 Y10.968 E0.02769 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.45


G1 F8640
G1 X11.220 Y10.259 E-0.23160 ; wipe and retract
G1 X10.594 Y10.259 E-0.14454 ; wipe and retract
G1 X11.741 Y11.406 E-0.37462 ; wipe and retract
G1 X11.741 Y11.446 E-0.00924 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z2.900 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.45
; printing object cube.stl id:0 copy 0
G1 X12.054 Y9.946 ; move to first perimeter point
G1 Z2.450 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X11.994 Y9.946 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y9.528 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.412 Y9.528 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.371 Y9.915 F10800.000 ; move inwards before travel
G1 F8640
G1 X12.456 Y12.819 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z3.050 F10800.000 ; lift Z
G1 X9.492 Y10.071 ; move to first infill point
G1 Z2.450 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X8.783 Y10.780 E0.02768 ; infill
G1 X8.783 Y11.406 E0.01728 ; infill
G1 X9.930 Y10.259 E0.04478 ; infill
G1 X10.556 Y10.259 E0.01728 ; infill
G1 X8.783 Y12.032 E0.06922 ; infill
G1 X8.783 Y12.658 E0.01728 ; infill
G1 X11.182 Y10.259 E0.09365 ; infill
G1 X11.741 Y10.259 E0.01543 ; infill
G1 X11.741 Y10.326 E0.00185 ; infill
G1 X8.783 Y13.284 E0.11548 ; infill
G1 X8.783 Y13.351 E0.00185 ; infill
G1 X9.342 Y13.351 E0.01543 ; infill
G1 X11.741 Y10.952 E0.09366 ; infill
G1 X11.741 Y11.578 E0.01728 ; infill
G1 X9.968 Y13.351 E0.06922 ; infill
G1 X10.594 Y13.351 E0.01728 ; infill
G1 X11.741 Y12.204 E0.04478 ; infill
G1 X11.741 Y12.830 E0.01728 ; infill
G1 X11.032 Y13.539 E0.02769 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.6


G1 F8640
G1 X11.741 Y12.830 E-0.23160 ; wipe and retract
G1 X11.741 Y12.204 E-0.14454 ; wipe and retract
G1 X10.594 Y13.351 E-0.37462 ; wipe and retract
G1 X10.554 Y13.351 E-0.00924 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z3.050 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.6
; printing object cube.stl id:0 copy 0
G1 X12.054 Y13.664 ; move to first perimeter point
G1 Z2.600 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X8.470 Y13.664 E0.09340 ; perimeter
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.604 E0.09533 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.472 Y14.082 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X8.052 Y14.082 E0.11518 ; perimeter
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.022 E0.11711 ; perimeter
M204 S1000 ; adjust acceleration
G1 X12.086 Y13.977 F10800.000 ; move inwards before travel
G1 F8640
G1 X9.181 Y14.067 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z3.200 F10800.000 ; lift Z
G1 X11.929 Y10.968 ; move to first infill point
G1 Z2.600 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X11.220 Y10.259 E0.02769 ; infill
G1 X10.594 Y10.259 E0.01728 ; infill
G1 X11.741 Y11.406 E0.04478 ; infill
G1 X11.741 Y12.032 E0.01728 ; infill
G1 X9.968 Y10.259 E0.06922 ; infill
G1 X9.342 Y10.259 E0.01728 ; infill
G1 X11.741 Y12.658 E0.09366 ; infill
G1 X11.741 Y13.284 E0.01728 ; infill
G1 X8.783 Y10.326 E0.11548 ; infill
G1 X8.783 Y10.952 E0.01728 ; infill
G1 X11.182 Y13.351 E0.09365 ; infill
G1 X10.556 Y13.351 E0.01728 ; infill
G1 X8.783 Y11.578 E0.06922 ; infill
G1 X8.783 Y12.204 E0.01728 ; infill
G1 X9.930 Y13.351 E0.04478 ; infill
G1 X9.304 Y13.351 E0.01728 ; infill
G1 X8.595 Y12.642 E0.02768 ; infill
; stop printing object cube.stl id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.75


G1 F8640
G1 X9.304 Y13.351 E-0.23156 ; wipe and retract
G1 X9.930 Y13.351 E-0.14454 ; wipe and retract
G1 X8.783 Y12.204 E-0.37458 ; wipe and retract
G1 X8.783 Y12.164 E-0.00932 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z3.200 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.75
; printing object cube.stl id:0 copy 0
G1 X8.470 Y13.664 ; move to first perimeter point
G1 Z2.750 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X8.470 Y9.946 E0.09690 ; perimeter
G1 X12.054 Y9.946 E0.09340 ; perimeter
G1 X12.054 Y13.664 E0.09690 ; perimeter
G1 X8.530 Y13.664 E0.09184 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.052 Y14.082 F10800.000 ; move to first perimeter point
M204 S800 ; adjust acceleration
G1 F900
G1 X8.052 Y9.528 E0.11867 ; perimeter
G1 X12.472 Y9.528 E0.11518 ; perimeter
G1 X12.472 Y14.082 E0.11867 ; perimeter
G1 X8.112 Y14.082 E0.11361 ; perimeter
M204 S1000 ; adjust acceleration
G1 X8.153 Y13.695 F10800.000 ; move inwards before travel
G1 F8640
G1 X8.068 Y10.791 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z3.350 F10800.000 ; lift Z
G1 X11.174 Y13.542 ; move to first infill point
G1 Z2.750 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X11.766 Y12.949 E0.01956 ; infill
G1 X11.766 Y12.420 E0.01237 ; infill
G1 X10.810 Y13.376 E0.03159 ; infill
G1 X10.280 Y13.376 E0.01237 ; infill
G1 X11.766 Y11.890 E0.04909 ; infill
G1 X11.766 Y11.360 E0.01237 ; infill
G1 X9.750 Y13.376 E0.06659 ; infill
G1 X9.221 Y13.376 E0.01237 ; infill
G1 X11.766 Y10.831 E0.08408 ; infill
G1 X11.766 Y10.301 E0.01237 ; infill
G1 X8.758 Y13.309 E0.09936 ; infill
G1 X8.758 Y12.779 E0.01237 ; infill
G1 X11.303 Y10.234 E0.08408 ; infill
G1 X10.774 Y10.234 E0.01237 ; infill
G1 X8.758 Y12.250 E0.06658 ; infill
G1 X8.758 Y11.720 E0.01237 ; infill
G1 X10.244 Y10.234 E0.04909 ; infill
G1 X9.714 Y10.234 E0.01237 ; infill
G1 X8.758 Y11.190 E0.03159 ; infill
G1 X8.758 Y10.661 E0.01237 ; infill
G1 X9.350 Y10.068 E0.01956 ; infill
; stop printing object cube.stl id:0 copy 0
G1 F8640;_WIPE
G1 X8.758 Y10.661 E-0.19337 ; wipe and retract
G1 F8640;_WIPE
G1 X8.758 Y11.190 E-0.12230 ; wipe and retract
G1 F8640;_WIPE
G1 X9.714 Y10.234 E-0.31228 ; wipe and retract
G1 F8640;_WIPE
G1 X10.244 Y10.234 E-0.12230 ; wipe and retract
G1 F8640;_WIPE
G1 X10.214 Y10.264 E-0.00974 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z3.350 F10800.000 ; lift Z
M107 ; disable fan
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z33.35 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 32.2
; filament used [cm3] = 0.1
; filament used [g] = 0.1
; filament cost = 0.0
; total filament used [g] = 0.1
; total filament cost = 0.0
; estimated printing time (normal mode) = 1m 47s
; estimated printing time (silent mode) = 1m 47s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.8
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "List of materials tested with standard PLA print settings:\n\nDas Filament\nEsun PLA\nEUMAKERS PLA\nFiberlogy HD-PLA\nFiberlogy PLA\nFloreon3D\nHatchbox PLA\nPlasty Mladec PLA\nPrimavalue PLA\nProto pasta Matte Fiber\nAmazonBasics PLA"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusa PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = "0.15mm QUALITY MK3";;
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.15
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_host = 
; print_settings_id = cube - Copy.3mf (cube.3mf (0.15mm QUALITY MK3))
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; printhost_apikey = 
; printhost_cafile = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210
; thin_walls = 0
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 7
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
