; generated by PrusaSlicer 2.1.1+win64 on 2020-01-31 at 16:07:07 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107 ; disable fan
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000 ; retract
G1 Z0.600 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.2
G1 X121.855 Y100.189 ; move to first skirt point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S1000 ; adjust acceleration
G1 F900
G1 X122.387 Y99.648 E0.02379 ; skirt
G1 X123.010 Y99.232 E0.02349 ; skirt
G1 X123.699 Y98.951 E0.02334 ; skirt
G1 X124.389 Y98.818 E0.02201 ; skirt
G1 X125.263 Y98.801 E0.02742 ; skirt
G1 X126.339 Y98.963 E0.03413 ; skirt
G1 X127.318 Y99.428 E0.03398 ; skirt
G1 X128.120 Y100.157 E0.03398 ; skirt
G1 X128.676 Y101.088 E0.03398 ; skirt
G1 X128.869 Y101.704 E0.02023 ; skirt
G1 X128.952 Y102.343 E0.02023 ; skirt
G1 X128.949 Y107.721 E0.16859 ; skirt
G1 X128.820 Y108.492 E0.02453 ; skirt
G1 X128.532 Y109.220 E0.02453 ; skirt
G1 X128.097 Y109.870 E0.02453 ; skirt
G1 X127.539 Y110.411 E0.02438 ; skirt
G1 X126.897 Y110.816 E0.02379 ; skirt
G1 X126.186 Y111.081 E0.02379 ; skirt
G1 X125.507 Y111.191 E0.02156 ; skirt
G1 X124.523 Y111.193 E0.03085 ; skirt
G1 X123.494 Y110.982 E0.03295 ; skirt
G1 X122.565 Y110.490 E0.03295 ; skirt
G1 X121.812 Y109.757 E0.03295 ; skirt
G1 X121.298 Y108.846 E0.03280 ; skirt
G1 X121.122 Y108.255 E0.01934 ; skirt
G1 X121.048 Y107.642 E0.01934 ; skirt
G1 X121.051 Y102.279 E0.16815 ; skirt
G1 X121.174 Y101.531 E0.02379 ; skirt
G1 X121.444 Y100.827 E0.02364 ; skirt
G1 X121.822 Y100.239 E0.02191 ; skirt
G1 X122.138 Y100.446 F10800.000 ; move to first skirt point
G1 F900
G1 X122.651 Y99.919 E0.02305 ; skirt
G1 X123.215 Y99.550 E0.02113 ; skirt
G1 X123.837 Y99.304 E0.02099 ; skirt
G1 X124.452 Y99.191 E0.01959 ; skirt
G1 X125.263 Y99.178 E0.02542 ; skirt
G1 X126.242 Y99.327 E0.03107 ; skirt
G1 X127.135 Y99.759 E0.03107 ; skirt
G1 X127.862 Y100.439 E0.03121 ; skirt
G1 X128.354 Y101.299 E0.03107 ; skirt
G1 X128.576 Y102.383 E0.03470 ; skirt
G1 X128.572 Y107.709 E0.16699 ; skirt
G1 X128.453 Y108.404 E0.02212 ; skirt
G1 X128.190 Y109.059 E0.02212 ; skirt
G1 X127.795 Y109.643 E0.02212 ; skirt
G1 X127.282 Y110.134 E0.02226 ; skirt
G1 X126.701 Y110.492 E0.02141 ; skirt
G1 X126.058 Y110.724 E0.02141 ; skirt
G1 X125.458 Y110.816 E0.01903 ; skirt
G1 X124.535 Y110.816 E0.02895 ; skirt
G1 X123.596 Y110.618 E0.03010 ; skirt
G1 X122.752 Y110.160 E0.03010 ; skirt
G1 X122.078 Y109.483 E0.02996 ; skirt
G1 X121.622 Y108.638 E0.03010 ; skirt
G1 X121.424 Y107.603 E0.03303 ; skirt
G1 X121.428 Y102.291 E0.16657 ; skirt
G1 X121.541 Y101.617 E0.02141 ; skirt
G1 X121.791 Y100.977 E0.02156 ; skirt
G1 X122.105 Y100.496 E0.01800 ; skirt
G1 X122.472 Y100.625 F10800.000 ; move to first skirt point
G1 F900
G1 X122.910 Y100.195 E0.01923 ; skirt
G1 X123.412 Y99.873 E0.01870 ; skirt
G1 X123.968 Y99.659 E0.01870 ; skirt
G1 X124.506 Y99.565 E0.01712 ; skirt
G1 X125.262 Y99.555 E0.02372 ; skirt
G1 X126.147 Y99.692 E0.02806 ; skirt
G1 X126.952 Y100.092 E0.02819 ; skirt
G1 X127.597 Y100.712 E0.02806 ; skirt
G1 X128.027 Y101.502 E0.02819 ; skirt
G1 X128.200 Y102.419 E0.02924 ; skirt
G1 X128.194 Y107.697 E0.16550 ; skirt
G1 X128.084 Y108.322 E0.01989 ; skirt
G1 X127.845 Y108.905 E0.01976 ; skirt
G1 X127.487 Y109.424 E0.01976 ; skirt
G1 X127.027 Y109.854 E0.01976 ; skirt
G1 X126.505 Y110.168 E0.01910 ; skirt
G1 X125.933 Y110.366 E0.01897 ; skirt
G1 X124.547 Y110.438 E0.04352 ; skirt
G1 X123.701 Y110.255 E0.02714 ; skirt
G1 X122.945 Y109.833 E0.02714 ; skirt
G1 X122.345 Y109.209 E0.02714 ; skirt
G1 X121.953 Y108.442 E0.02701 ; skirt
G1 X121.800 Y107.573 E0.02767 ; skirt
G1 X121.806 Y102.303 E0.16524 ; skirt
G1 X121.910 Y101.699 E0.01923 ; skirt
G1 X122.135 Y101.132 E0.01910 ; skirt
G1 X122.439 Y100.675 E0.01722 ; skirt
G1 F8640
G1 X122.910 Y100.195 E-0.15522 ; wipe and retract
G1 X123.412 Y99.873 E-0.13774 ; wipe and retract
G1 X123.968 Y99.659 E-0.13774 ; wipe and retract
G1 X124.506 Y99.565 E-0.12605 ; wipe and retract
G1 X125.262 Y99.555 E-0.17467 ; wipe and retract
G1 X125.385 Y99.574 E-0.02858 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
G1 X124.102 Y100.013 ; move to first skirt point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X125.262 Y99.932 E0.03647 ; skirt
G1 X126.052 Y100.058 E0.02508 ; skirt
G1 X126.765 Y100.421 E0.02508 ; skirt
G1 X127.329 Y100.983 E0.02496 ; skirt
G1 X127.695 Y101.695 E0.02508 ; skirt
G1 X127.823 Y102.445 E0.02386 ; skirt
G1 X127.818 Y107.680 E0.16415 ; skirt
G1 X127.719 Y108.228 E0.01746 ; skirt
G1 X127.504 Y108.742 E0.01746 ; skirt
G1 X127.184 Y109.197 E0.01746 ; skirt
G1 X126.773 Y109.573 E0.01746 ; skirt
G1 X126.316 Y109.840 E0.01660 ; skirt
G1 X125.813 Y110.007 E0.01660 ; skirt
G1 X124.564 Y110.062 E0.03921 ; skirt
G1 X123.814 Y109.894 E0.02410 ; skirt
G1 X123.147 Y109.512 E0.02410 ; skirt
G1 X122.623 Y108.949 E0.02410 ; skirt
G1 X122.290 Y108.256 E0.02410 ; skirt
G1 X122.177 Y107.547 E0.02251 ; skirt
G1 X122.182 Y102.320 E0.16391 ; skirt
G1 X122.277 Y101.787 E0.01697 ; skirt
G1 X122.479 Y101.289 E0.01684 ; skirt
G1 X122.782 Y100.841 E0.01697 ; skirt
G1 X123.170 Y100.470 E0.01684 ; skirt
G1 X123.613 Y100.194 E0.01635 ; skirt
G1 X124.046 Y100.034 E0.01447 ; skirt
G1 X123.428 Y100.748 F10800.000 ; move to first skirt point
G1 F900
G1 X124.233 Y100.369 E0.02788 ; skirt
G1 X125.262 Y100.309 E0.03232 ; skirt
G1 X125.948 Y100.421 E0.02179 ; skirt
G1 X126.567 Y100.744 E0.02191 ; skirt
G1 X127.053 Y101.246 E0.02191 ; skirt
G1 X127.356 Y101.876 E0.02191 ; skirt
G1 X127.447 Y102.466 E0.01873 ; skirt
G1 X127.441 Y107.659 E0.16282 ; skirt
G1 X127.354 Y108.133 E0.01510 ; skirt
G1 X127.165 Y108.576 E0.01510 ; skirt
G1 X126.884 Y108.967 E0.01510 ; skirt
G1 X126.525 Y109.287 E0.01510 ; skirt
G1 X125.700 Y109.646 E0.02822 ; skirt
G1 X124.585 Y109.685 E0.03498 ; skirt
G1 X123.932 Y109.535 E0.02100 ; skirt
G1 X123.355 Y109.195 E0.02100 ; skirt
G1 X122.908 Y108.696 E0.02100 ; skirt
G1 X122.632 Y108.086 E0.02100 ; skirt
G1 X122.553 Y107.530 E0.01760 ; skirt
G1 X122.559 Y102.341 E0.16270 ; skirt
G1 X122.820 Y101.450 E0.02911 ; skirt
G1 X123.389 Y100.793 E0.02723 ; skirt
; printing object cube.stl id:0 copy 0 /////////////////////////////////////////////////////////////////////
G1 F8640
G1 X124.233 Y100.369 E-0.21805 ; wipe and retract
G1 X125.262 Y100.309 E-0.23805 ; wipe and retract
G1 X125.948 Y100.421 E-0.16050 ; wipe and retract
G1 X126.499 Y100.708 E-0.14339 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
G1 X124.952 Y102.708 ; move to first perimeter point
G1 Z0.200 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X125.048 Y102.708 E0.00302 ; perimeter
G1 X125.048 Y107.292 E0.14374 ; perimeter
G1 X124.952 Y107.292 E0.00302 ; perimeter
G1 X124.952 Y102.768 E0.14186 ; perimeter
G1 X125.036 Y102.755 F10800.000 ; move inwards before travel
; stop printing object cube.stl id:0 copy 0 /////////////////////////////////////////////////////////////////////
M106 S255 ; enable fan
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.35


G1 F8640
G1 X125.048 Y102.708 E-0.02621 ; wipe and retract
G1 X125.048 Y105.886 E-0.73379 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.800 F10800.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.35
M104 S210 ; set temperature
G1 X126.339 Y98.963 ; move to first skirt point
G1 Z0.350 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
G1 F900
G1 X127.318 Y99.428 E0.02621 ; skirt
G1 X128.120 Y100.157 E0.02621 ; skirt
G1 X128.676 Y101.088 E0.02621 ; skirt
G1 X128.869 Y101.704 E0.01560 ; skirt
G1 X128.952 Y102.343 E0.01560 ; skirt
G1 X128.949 Y107.721 E0.13004 ; skirt
G1 X128.820 Y108.492 E0.01892 ; skirt
G1 X128.532 Y109.220 E0.01892 ; skirt
G1 X128.097 Y109.870 E0.01892 ; skirt
G1 X127.539 Y110.411 E0.01881 ; skirt
G1 X126.897 Y110.816 E0.01835 ; skirt
G1 X126.186 Y111.081 E0.01835 ; skirt
G1 X125.507 Y111.191 E0.01663 ; skirt
G1 X124.523 Y111.193 E0.02380 ; skirt
G1 X123.494 Y110.982 E0.02542 ; skirt
G1 X122.565 Y110.490 E0.02542 ; skirt
G1 X121.812 Y109.757 E0.02542 ; skirt
G1 X121.298 Y108.846 E0.02530 ; skirt
G1 X121.122 Y108.255 E0.01492 ; skirt
G1 X121.048 Y107.642 E0.01492 ; skirt
G1 X121.051 Y102.279 E0.12970 ; skirt
G1 X121.174 Y101.531 E0.01835 ; skirt
G1 X121.444 Y100.827 E0.01823 ; skirt
G1 X121.855 Y100.189 E0.01835 ; skirt
G1 X122.387 Y99.648 E0.01835 ; skirt
G1 X123.010 Y99.232 E0.01812 ; skirt
G1 X123.699 Y98.951 E0.01801 ; skirt
G1 X124.389 Y98.818 E0.01698 ; skirt
G1 X125.263 Y98.801 E0.02115 ; skirt
G1 X126.280 Y98.954 E0.02488 ; skirt
; printing object cube.stl id:0 copy 0 /////////////////////////////////////////////////////////////////////
G1 F8640
G1 X127.318 Y99.428 E-0.26355 ; wipe and retract
G1 X128.120 Y100.157 E-0.25027 ; wipe and retract
G1 X128.667 Y101.073 E-0.24618 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.950 F10800.000 ; lift Z
G1 X125.033 Y102.723 ; move to first perimeter point
G1 Z0.350 ; restore layer Z
G1 E0.80000 F2100.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X125.033 Y107.277 E0.11867 ; perimeter
G1 X124.967 Y107.277 E0.00173 ; perimeter
G1 X124.973 Y102.723 E0.11867 ; perimeter
M204 S1000 ; adjust acceleration
G1 X124.687 Y102.523 F10800.000 ; move inwards before travel
; stop printing object cube.stl id:0 copy 0 /////////////////////////////////////////////////////////////////////
G1 F8640;_WIPE
G1 X125.017 Y106.014 E-0.76000 ; wipe and retract
G1 E-0.04000 F2100.00000 ; retract
G1 Z0.950 F10800.000 ; lift Z
M107 ; disable fan
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.95 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 6.0
; filament used [cm3] = 0.0
; filament used [g] = 0.0
; filament cost = 0.0
; total filament used [g] = 0.0
; total filament cost = 0.0
; estimated printing time (normal mode) = 28s
; estimated printing time (silent mode) = 28s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.8
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "List of materials tested with standard PLA print settings:\n\nDas Filament\nEsun PLA\nEUMAKERS PLA\nFiberlogy HD-PLA\nFiberlogy PLA\nFloreon3D\nHatchbox PLA\nPlasty Mladec PLA\nPrimavalue PLA\nProto pasta Matte Fiber\nAmazonBasics PLA"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusa PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.15
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_host = 
; print_settings_id = 0.15mm QUALITY MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; printhost_apikey = 
; printhost_cafile = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210
; thin_walls = 0
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 7
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
